package main

import (
	"bytes"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"strings"
	"time"
)

type CartItem struct {
	ProductID   string  `json:"product_id"`
	ProductName string  `json:"product_name"`
	Quantity    int     `json:"quantity"`
	UnitPrice   float64 `json:"unit_price"`
}

type OrderRequest struct {
	Cart []CartItem `json:"cart"`
}

type OrderResponse struct {
	OrderID        string     `json:"order_id"`
	Cart           []CartItem `json:"cart"`
	TotalPrice     float64    `json:"total_price"`
	OrderStatus    string     `json:"order_status"`
	PaymentStatus  string     `json:"payment_status"`
	PaymentMessage string     `json:"payment_message"`
}

var ordersDB []OrderResponse

func orderHandler(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Access-Control-Allow-Origin", "*")
	w.Header().Set("Access-Control-Allow-Methods", "GET, POST, DELETE, OPTIONS")
	w.Header().Set("Access-Control-Allow-Headers", "Content-Type, Authorization")
	w.Header().Set("Content-Type", "application/json")

	if r.Method == http.MethodOptions {
		w.WriteHeader(http.StatusOK)
		return
	}

	if r.Method == http.MethodGet {
		json.NewEncoder(w).Encode(ordersDB)
		return
	}

	if r.Method == http.MethodDelete {
		orderID := r.URL.Query().Get("id")
		if orderID == "" {
			http.Error(w, `{"error": "Missing order id"}`, http.StatusBadRequest)
			return
		}

		var updatedDB []OrderResponse
		for _, order := range ordersDB {
			if order.OrderID != orderID {
				updatedDB = append(updatedDB, order)
			}
		}
		ordersDB = updatedDB

		w.WriteHeader(http.StatusOK)
		fmt.Fprintf(w, `{"message": "Order %s deleted successfully"}`, orderID)
		return
	}

	if r.Method == http.MethodPost {
		var req OrderRequest
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			http.Error(w, `{"error": "Invalid JSON"}`, http.StatusBadRequest)
			return
		}

		var totalAmount float64
		for _, item := range req.Cart {
			totalAmount += float64(item.Quantity) * item.UnitPrice
		}

		orderIDNum := time.Now().Unix()
		orderIDString := fmt.Sprintf("ORD-%d", orderIDNum)

		// ---------------------------------------------------------
		// EXTRACT USER ID FROM JWT TOKEN
		// ---------------------------------------------------------
		userID := float64(1) // Fallback default
		authHeader := r.Header.Get("Authorization")
		if len(authHeader) > 7 && strings.HasPrefix(authHeader, "Bearer ") {
			tokenString := authHeader[7:]
			parts := strings.Split(tokenString, ".")
			if len(parts) == 3 {
				// Base64 decode the payload section of the JWT
				payload, err := base64.RawURLEncoding.DecodeString(parts[1])
				if err == nil {
					var claims map[string]interface{}
					if err := json.Unmarshal(payload, &claims); err == nil {
						// Extract the "id" claim generated by Java JwtUtil
						if idClaim, ok := claims["id"].(float64); ok {
							userID = idClaim
						}
					}
				}
			}
		}

		// INTER-SERVICE COMMUNICATION
		paymentURL := os.Getenv("PAYMENT_SERVICE_URL")
		if paymentURL == "" {
			// CHANGED: Point to the new internal endpoint
			paymentURL = "http://payment-service:8083/payments/internal"
		}

		paymentPayload, _ := json.Marshal(map[string]interface{}{
			"orderId":       orderIDNum,
			"userId":        userID, // This uses the ID extracted from the JWT earlier
			"amount":        totalAmount,
			"paymentMethod": "CREDIT_CARD",
		})

		reqToPayment, _ := http.NewRequest("POST", paymentURL, bytes.NewBuffer(paymentPayload))
		reqToPayment.Header.Set("Content-Type", "application/json")

		// We still send the Authorization header just in case, but it won't trigger 403 anymore
		if authHeader != "" {
			reqToPayment.Header.Set("Authorization", authHeader)
		}

		client := &http.Client{Timeout: 10 * time.Second}
		resp, err := client.Do(reqToPayment)

		paymentStatus := "Pending Payment"
		paymentMessage := "Failed to reach payment service"

		if err == nil {
			defer resp.Body.Close()
			paymentData, _ := io.ReadAll(resp.Body)

			if resp.StatusCode == http.StatusCreated || resp.StatusCode == http.StatusOK {
				var paymentJSON map[string]interface{}
				json.Unmarshal(paymentData, &paymentJSON)

				if txnID, ok := paymentJSON["id"].(float64); ok {
					paymentStatus = fmt.Sprintf("Paid (ID: %v)", txnID)
				}

				paymentMessage = "Order is sent to make the payment, connected with payment-service"
			} else {
				paymentMessage = fmt.Sprintf("Payment failed with status %d: %s", resp.StatusCode, string(paymentData))
			}
		}

		newOrder := OrderResponse{
			OrderID:        orderIDString,
			Cart:           req.Cart,
			TotalPrice:     totalAmount,
			OrderStatus:    "Confirmed",
			PaymentStatus:  paymentStatus,
			PaymentMessage: paymentMessage,
		}

		ordersDB = append(ordersDB, newOrder)

		w.WriteHeader(http.StatusCreated)
		json.NewEncoder(w).Encode(newOrder)
		return
	}

	http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
}

func healthHandler(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusOK)
	fmt.Fprintf(w, "Healthy")
}

func main() {
	http.HandleFunc("/orders", orderHandler)
	http.HandleFunc("/health", healthHandler)

	fmt.Println("Order Service is running on port 8080...")
	log.Fatal(http.ListenAndServe(":8080", nil))
}
