apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: local-product-service:v3
        imagePullPolicy: Never
        ports:
        - containerPort: 5000

        volumeMounts:
        - name: upload-storage
          mountPath: /app/uploads

      volumes:
      - name: upload-storage
        hostPath:
          path: /data/uploads
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000